name: Build and deploy

on:
  push:
    branches: [main]
    paths: [package.json, bun.lock, wrangler.toml, .github/workflows/publish.yml, public/**, src/**]
  workflow_dispatch:

concurrency:
  group: dist
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Install Bun
        uses: oven-sh/setup-bun@v2.0.2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run test
        run: bun run test
  deploy:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        deployments: write
      needs: test
      steps:
        - name: Checkout
          uses: actions/checkout@v5.0.0

        - name: Install Bun
          uses: oven-sh/setup-bun@v2.0.2
          with:
            bun-version: latest

        - name: Install dependencies
          run: bun install --frozen-lockfile

        - name: Deploy
          uses: cloudflare/wrangler-action@v3.14.1
          with:
            accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            gitHubToken: ${{ secrets.GITHUB_TOKEN }}
            wranglerVersion: latest
            command: deploy
